<a href="https://colab.research.google.com/github/mirza-javed/ML-practice/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('/content/drive/MyDrive/ML Learning/sample_dataset_missing.csv')

In [4]:
df.head(5)

,ID,Name,Age,Gender,Salary,Joining Date,Is Active,Comments
0,1,Paul,25.0,Female,90041.86,1/31/2017,False,Creative
1,2,Paul,31.0,Male,90285.02,5/29/2019,False,Needs Improvement
2,3,Rachel,30.0,Male,84321.65,12/14/2022,False,Hardworking
3,4,Bob,45.0,Male,68189.99,9/5/2023,True,Fast Learner
4,5,Eve,34.0,Male,35428.35,5/19/2018,True,Dedicated

Looking missing values

In [5]:
df.isnull().sum()

ID              0
Name            4
Age             1
Gender          4
Salary          2
Joining Date    1
Is Active       2
Comments        0
dtype: int64

In [6]:
# Convert Joining Date to a proper date format
df['Joining Date'] = pd.to_datetime(df['Joining Date'], errors='coerce')

df['Age'] = df['Age'].fillna(df['Age'].median())
df['Salary'] = df['Salary'].fillna(df['Salary'].median())
df['Name'] = df['Name'].fillna(df['Name'].mode()[0])
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Is Active'] = df['Is Active'].fillna(df['Is Active'].mode()[0])
df['Comments'] = df['Comments'].fillna("Unknown")

print("All missing values are filled and saved")

All missing values are filled and saved

/tmp/ipykernel_16072/4237740401.py:8: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Is Active'] = df['Is Active'].fillna(df['Is Active'].mode()[0])

In [7]:
df.head()

,ID,Name,Age,Gender,Salary,Joining Date,Is Active,Comments
0,1,Paul,25.0,Female,90041.86,2017-01-31,False,Creative
1,2,Paul,31.0,Male,90285.02,2019-05-29,False,Needs Improvement
2,3,Rachel,30.0,Male,84321.65,2022-12-14,False,Hardworking
3,4,Bob,45.0,Male,68189.99,2023-09-05,True,Fast Learner
4,5,Eve,34.0,Male,35428.35,2018-05-19,True,Dedicated

In [8]:
df.isnull().sum()

ID              0
Name            0
Age             0
Gender          0
Salary          0
Joining Date    1
Is Active       0
Comments        0
dtype: int64

In [10]:
df['Joining Date'] = df['Joining Date'].fillna(df['Joining Date'].min())

df.isnull().sum()

ID              0
Name            0
Age             0
Gender          0
Salary          0
Joining Date    0
Is Active       0
Comments        0
dtype: int64

In [11]:
df.head(5)

,ID,Name,Age,Gender,Salary,Joining Date,Is Active,Comments
0,1,Paul,25.0,Female,90041.86,2017-01-31,False,Creative
1,2,Paul,31.0,Male,90285.02,2019-05-29,False,Needs Improvement
2,3,Rachel,30.0,Male,84321.65,2022-12-14,False,Hardworking
3,4,Bob,45.0,Male,68189.99,2023-09-05,True,Fast Learner
4,5,Eve,34.0,Male,35428.35,2018-05-19,True,Dedicated

In [12]:
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
df['Is Active'] = le.fit_transform(df['Is Active'])

print(df.head(5))

   ID    Name   Age  Gender    Salary Joining Date  Is Active  \
0   1    Paul  25.0       0  90041.86   2017-01-31          0
1   2    Paul  31.0       1  90285.02   2019-05-29          0
2   3  Rachel  30.0       1  84321.65   2022-12-14          0
3   4     Bob  45.0       1  68189.99   2023-09-05          1
4   5     Eve  34.0       1  35428.35   2018-05-19          1

            Comments
0           Creative
1  Needs Improvement
2        Hardworking
3       Fast Learner
4          Dedicated

In [13]:
import pandas as pd

# df = pd.read_csv("sample_dataset_1000.csv")  # Load dataset

# Apply pd.get_dummies for one-hot encoding
encoded_df = pd.get_dummies(df['Is Active'], prefix='Is_Active')

# Concatenate with original dataset and drop old column
df = pd.concat([df, encoded_df], axis=1).drop(columns=['Is Active'])

df.to_csv("cleaned_dataset.csv", index=False)  # Save updated dataset

print("Is Active converted to One-Hot Encoding and saved!")

Is Active converted to One-Hot Encoding and saved!

In [15]:
df1 = pd.read_csv("cleaned_dataset.csv")
df1.head()

,ID,Name,Age,Gender,Salary,Joining Date,Comments,Is_Active_0,Is_Active_1
0,1,Paul,25.0,0,90041.86,2017-01-31,Creative,True,False
1,2,Paul,31.0,1,90285.02,2019-05-29,Needs Improvement,True,False
2,3,Rachel,30.0,1,84321.65,2022-12-14,Hardworking,True,False
3,4,Bob,45.0,1,68189.99,2023-09-05,Fast Learner,False,True
4,5,Eve,34.0,1,35428.35,2018-05-19,Dedicated,False,True